version: '3'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - "./web:/projects"
    tty: true
  api:
    build: ./api
    volumes:
      - "./api/:/api"
    tty: true
    scale: 2
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - api
    links:
      - api
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
